package com.sfeir.tutorials.client.widget;

import com.google.gwt.cell.client.AbstractCell;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.sfeir.tutorials.shared.User;

/**
 * This is the class allowing to format a panel cell associated to a given user
 * 
 * @author Oussama Zoghlami
 * 
 */
public class UserCell extends AbstractCell<User> {

	/**
	 * The html of the image used for contacts.
	 */
	private final String imageHtml = "<img border=\"0\" style=\"width: 32px; height: 32px; background: url(data:image/jpeg;base64,"
			+ "/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAZAAA/+ENSWh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPS"
			+ "Lvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUg"
			+ "WE1QIENvcmUgNC4yLjItYzA2MyA1My4zNTI2MjQsIDIwMDgvMDcvMzAtMTg6MDU6NDEgICAgICAgICI+CiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly"
			+ "93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICB4bWxuczpkYz0iaHR0"
			+ "cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iCiAgICB4bWxuczp4bXBSaWdodHM9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9yaWdodHMvIg"
			+ "ogICAgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIgogICAgeG1sbnM6SXB0YzR4bXBDb3JlPSJodHRwOi8v"
			+ "aXB0Yy5vcmcvc3RkL0lwdGM0eG1wQ29yZS8xLjAveG1sbnMvIgogICB4bXBSaWdodHM6TWFya2VkPSJGYWxzZSIKICAgeG1wUmlnaHRzOldlYlN0YXRlbW"
			+ "VudD0iIgogICBwaG90b3Nob3A6QXV0aG9yc1Bvc2l0aW9uPSIiPgogICA8ZGM6cmlnaHRzPgogICAgPHJkZjpBbHQ+CiAgICAgPHJkZjpsaSB4bWw6bGFu"
			+ "Zz0ieC1kZWZhdWx0Ii8+CiAgICA8L3JkZjpBbHQ+CiAgIDwvZGM6cmlnaHRzPgogICA8ZGM6Y3JlYXRvcj4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bG"
			+ "kvPgogICAgPC9yZGY6U2VxPgogICA8L2RjOmNyZWF0b3I+CiAgIDxkYzp0aXRsZT4KICAgIDxyZGY6QWx0PgogICAgIDxyZGY6bGkgeG1sOmxhbmc9Ingt"
			+ "ZGVmYXVsdCIvPgogICAgPC9yZGY6QWx0PgogICA8L2RjOnRpdGxlPgogICA8eG1wUmlnaHRzOlVzYWdlVGVybXM+CiAgICA8cmRmOkFsdD4KICAgICA8cm"
			+ "RmOmxpIHhtbDpsYW5nPSJ4LWRlZmF1bHQiLz4KICAgIDwvcmRmOkFsdD4KICAgPC94bXBSaWdodHM6VXNhZ2VUZXJtcz4KICAgPElwdGM0eG1wQ29yZTpD"
			+ "cmVhdG9yQ29udGFjdEluZm8KICAgIElwdGM0eG1wQ29yZTpDaUFkckV4dGFkcj0iIgogICAgSXB0YzR4bXBDb3JlOkNpQWRyQ2l0eT0iIgogICAgSXB0YzR"
			+ "4bXBDb3JlOkNpQWRyUmVnaW9uPSIiCiAgICBJcHRjNHhtcENvcmU6Q2lBZHJQY29kZT0iIgogICAgSXB0YzR4bXBDb3JlOkNpQWRyQ3RyeT0iIgogICAgS"
			+ "XB0YzR4bXBDb3JlOkNpVGVsV29yaz0iIgogICAgSXB0YzR4bXBDb3JlOkNpRW1haWxXb3JrPSIiCiAgICBJcHRjNHhtcENvcmU6Q2lVcmxXb3JrPSIiLz4"
			+ "KICA8L3JkZjpEZXNjcmlwdGlvbj4KIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICA"
			+ "gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA"
			+ "gICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI"
			+ "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0idyI/Pv/uAA5BZG9iZQB"
			+ "kwAAAAAH/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgMDAwMDAwMDAwMBAQEBAQEBAgEBAgICA"
			+ "QICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA//AABEIACAAIAMBEQACEQEDEQH/xABvAAEAAgMBAAAAAAAAAAA"
			+ "AAAAKBgcABQgLAQEBAQAAAAAAAAAAAAAAAAAAAQIQAAAHAAEBBQgDAAAAAAAAAAECAwQFBgcIABESExUJIbbWN3eXGFgUFhcRAQEBAQEBAAAAAAAAAAAAA"
			+ "AABETFRIf/aAAwDAQACEQMRAD8AUtjeN5DKZDlUnJ5Vm8jJSOb0Z9ISD6jVh29fPXdYi3Dt48duItRdy6crqGOoocxjnOYRERERHrMkyfATv1duZNqieUV"
			+ "5wPEo+q5HQcnWYV6RVotLq1dstltRo5pIzEhI2ZjEhNJMmazz+O2btl0ERIQTqFOcwdy5PBr/AEmua1pW5PZ7hO3xtW1/PNdlf6iyVvVMq1is1XtT9FU0D"
			+ "KRtnfxJptZk6fpkbOWzlddEE1O+mUhyiJmTwLU2TG8hi8h1WTjMqzeOko7N7y+j5BjRqw0esXrSsSjho8Zu28Wmu2dNl0ynTUIYpyHKAgICAD1LJl+CyMN"
			+ "+SmPfS3PvdKI6s5ADj1k8d0PDud2uyd+UCSjdimHWpUWwpFUIhK1iYXM1SYmDwEk039ccMzMVyE7xQ8IpgEQOHVEd9JDGNG3/AJx44TOlvK0ssscXrFys6"
			+ "qayravVipyTRdYwgVBQh38y8USYtSH7pTLOAExgKUR6B9O5fJTYfpboPulL9S8opVjyPwPjzx5yWxbjsOd5ZEoZNnrgy91tUTCLKomqsSQp2jB05LIPgMc"
			+ "BAARSUER9nScgFx68Pqoce+a16yehcdyrWWq4sa3rSWsOmC8SlbJa0+St1Ieus3yDeUVrsMSC8QrpYEyuVnBhSJ4ZQUUojPoceqzg3BHQtVrfIGGkWlM2h"
			+ "vU009RgozzyRo7+pefmQZSsU37ZZxWJ3zztXOzBZVFw3RMKJyd46YNWJys438m+POuz+BbXnWqR58q0Q6idSs0c/lGgJVKU8UJCDFZOajjIicCmBdun3Td"
			+ "oD7QEOpeUeZTzVzTm3qfKfdrI9w/kzoUMhqFzgaRYE8q0qwQx8/rk69gaK1rMg3gHMerWmlUjWaTEzYwoHbEIYomAe8MlmT6OW/xp5i/qtyV+xum/DHV2e"
			+ "jPxp5i/qtyV+xum/DHTZ6OkuH2U81c15PYVZmuEcmaHGf6lRoi3WE2T6XARiFFnLLGxN2b2GSWr7ZmjWnVYeOk34uDggDYxxOIAHaEtmdH/2Q==) no-re"
			+ "peat 0px 0px;\" src=\"http://gwt.google.com/samples/Showcase/showcase/clear.cache.gif\" onload=\"this.__gwtLastUnhandl"
			+ "edEvent=&quot;load&quot;;\">";

	public UserCell() {
	}

	@Override
	public void render(com.google.gwt.cell.client.Cell.Context context, User user, SafeHtmlBuilder sb) {
		// Value can be null, so do a null check..
		if (user == null) {
			return;
		}

		sb.appendHtmlConstant("<table class=\"condensed-table\">");

		// Add the contact image.
		sb.appendHtmlConstant("<tr><td rowspan='3'>");
		sb.appendHtmlConstant(imageHtml);
		sb.appendHtmlConstant("</td>");

		// Add the name and address.
		sb.appendHtmlConstant("<td style='font-size:95%;width:270px;'>");
		sb.appendEscaped(user.getName() + " " + user.getSurname());
		sb.appendHtmlConstant("</td></tr><tr><td>");
		sb.appendEscaped(user.getEmail());
		sb.appendHtmlConstant("</td></tr></table>");
	}

}
